/**
 * Reference content: glossary definitions and primary-source citations.
 * Kept as data so the UI renders consistently and every claim is sourced.
 */

export interface GlossaryEntry {
  term: string;
  symbol?: string;
  definition: string;
}

export const GLOSSARY: GlossaryEntry[] = [
  {
    term: 'Private key',
    symbol: 'd',
    definition:
      'A secret integer in [1, n−1]. Whoever knows d can sign. The entire security of ECDSA is keeping d secret.',
  },
  {
    term: 'Public key',
    symbol: 'Q = d·G',
    definition:
      'The point you get by adding the generator G to itself d times. Safe to publish: deriving d from Q is the hard ECDLP.',
  },
  {
    term: 'Generator / base point',
    symbol: 'G',
    definition:
      'A fixed, public curve point that generates the group. Every public key is some multiple of G.',
  },
  {
    term: 'Scalar multiplication',
    symbol: 'k·G',
    definition:
      'Repeated point addition (G + G + … k times), done in O(log k) by double-and-add. Easy forward, believed infeasible to reverse.',
  },
  {
    term: 'ECDLP',
    definition:
      'Elliptic Curve Discrete Logarithm Problem: given G and Q = d·G, find d. No efficient classical algorithm is known — this is why ECDSA is secure.',
  },
  {
    term: 'Nonce',
    symbol: 'k',
    definition:
      '“Number used once.” A fresh per-signature secret scalar. It must be unpredictable AND never repeated — reuse leaks d outright.',
  },
  {
    term: 'Curve order',
    symbol: 'n',
    definition:
      'The number of points in the group generated by G. All signature arithmetic on r and s is done modulo n.',
  },
  {
    term: 'Modular inverse',
    symbol: 'a⁻¹ mod n',
    definition:
      'The number that multiplies with a to give 1 modulo n. Signing needs k⁻¹; recovery needs (s1−s2)⁻¹ and r⁻¹.',
  },
  {
    term: 'Message hash',
    symbol: 'e',
    definition:
      'The message digest (here SHA-256), taken as an integer and reduced to the leftmost bits of n. ECDSA signs e, not the raw message.',
  },
  {
    term: 'Signature',
    symbol: '(r, s)',
    definition:
      'r is the x-coordinate of k·G (mod n); s = k⁻¹·(e + r·d) mod n binds the hash and the key to that nonce.',
  },
];

export interface Citation {
  id: string;
  title: string;
  source: string;
  year: string;
  note: string;
  url: string;
}

export const CITATIONS: Citation[] = [
  {
    id: 'fips186-5',
    title: 'FIPS 186-5 — Digital Signature Standard (DSS)',
    source: 'NIST',
    year: '2023',
    note: 'The authoritative U.S. standard defining ECDSA, approved curves, and signing/verification procedures.',
    url: 'https://csrc.nist.gov/pubs/fips/186-5/final',
  },
  {
    id: 'sec1',
    title: 'SEC 1: Elliptic Curve Cryptography',
    source: 'SECG (Certicom)',
    year: '2009',
    note: 'Defines the ECDSA scheme and point/scalar encodings used across the ecosystem.',
    url: 'https://www.secg.org/sec1-v2.pdf',
  },
  {
    id: 'sec2',
    title: 'SEC 2: Recommended Elliptic Curve Domain Parameters',
    source: 'SECG (Certicom)',
    year: '2010',
    note: 'Source of the secp256k1 and secp256r1 (P-256) parameters used in this lab.',
    url: 'https://www.secg.org/sec2-v2.pdf',
  },
  {
    id: 'rfc6979',
    title: 'RFC 6979 — Deterministic Usage of DSA and ECDSA',
    source: 'T. Pornin',
    year: '2013',
    note: 'Derives the nonce k from the key and message via HMAC, eliminating RNG-failure nonce reuse. Verified here against Appendix A.2.5.',
    url: 'https://datatracker.ietf.org/doc/html/rfc6979',
  },
  {
    id: 'ps3',
    title: 'Console Hacking 2010 — PS3 Epic Fail',
    source: 'fail0verflow, 27C3',
    year: '2010',
    note: 'Sony reused a constant ECDSA nonce in firmware signing; the master private key was recovered exactly as shown in Exhibit 4.',
    url: 'https://media.ccc.de/v/27c3-4087-en-console_hacking_2010',
  },
  {
    id: 'corbellini',
    title: 'Elliptic Curve Cryptography: a gentle introduction',
    source: 'A. Corbellini',
    year: '2015',
    note: 'Clear treatment of the group law and finite-field curves; basis for the toy-curve geometry here.',
    url: 'https://andrea.corbellini.name/2015/05/17/elliptic-curve-cryptography-a-gentle-introduction/',
  },
];
